import Head from 'next/head'
import Image from 'next/image'
import { useState, useEffect } from 'react'
import styles from '../styles/Home.module.css'
import Web3 from 'web3'
import { contractAbi, contractAddress } from './config'

const web3 = new Web3(Web3.givenProvider)

export default function Home() {
  const [tokenID, setTokenID] = useState()
  const [Amount, setAmount] = useState()
  const [Data, setData] = useState()
  const [tokenURI, setTokenURI] = useState()
  const [colName, setColName] = useState()

  const MinterContract = new web3.eth.Contract(contractAbi, contractAddress)

  const handleConnect = () => {
    Web3.givenProvider.request({ method: 'eth_requestAccounts' })
  }

  useEffect(() => {
    handleConnect()
  }, [])

  const handleGetMember = async () => {
    console.log(Web3.givenProvider?.selectedAddress)
    const _member = await workshopContract.methods.members(Web3.givenProvider?.selectedAddress).call()
    setMember(_member)
    console.log("Member: ", _member)
  }

  const handleMinter = () => {
    MinterContract.methods.createToken(tokenID, Amount, Data, tokenURI, colName)
      .send({ from: Web3.givenProvider?.selectedAddress, gasPrice: 4500000000 })
      .on('receipt', () => {
        alert('Sukses')
      })
      .on('error', () => {
        alert('Error')
      })
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Tes Minting</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Tes Minting
        </h1>

        <div>
          <input style={{
            height: '3rem',
            padding: '2px 4px',
            marginRight: '8px'
          }} type="text" placeholder="tokenID" value={tokenID} onChange={(e) => setTokenID(e.target.value)} />
          <input style={{
            height: '3rem',
            padding: '2px 4px',
            marginRight: '8px'
          }} type="text" placeholder="Amount" value={Amount} onChange={(e) => setAmount(e.target.value)} />
          <input style={{
            height: '3rem',
            padding: '2px 4px',
            marginRight: '8px'
          }} type="text" placeholder="Data" value={Data} onChange={(e) => setData(e.target.value)} />
          <input style={{
            height: '3rem',
            padding: '2px 4px',
            marginRight: '8px'
          }} type="text" placeholder="tokenURI" value={tokenURI} onChange={(e) => setTokenURI(e.target.value)} />
          <input style={{
            height: '3rem',
            padding: '2px 4px',
            marginRight: '8px'
          }}  type="text" placeholder="Collection Name" value={colName} onChange={(e) => setColName(e.target.value)} />
          <button style={{ height: '3rem' }} onClick={handleMinter}>Mint!</button>
        </div>
      </main>
    </div>
  )
}
